"""Update db.

Revision ID: 94382a9dbf82
Revises: faa1233bac63
Create Date: 2024-06-15 09:47:19.584101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94382a9dbf82'
down_revision = 'faa1233bac63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
